- hosts: local
  remote_user: cloud
  sudo: yes

  vars:
    jenkins_url: "http://127.0.0.1:8080"

  tasks:
    - name: jenkins key server is known
      apt_key:
        url="http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key"
        state=present

    - name: jenkins apt server is known
      apt_repository:
        repo="deb http://pkg.jenkins-ci.org/debian binary/"
        state=present

    - name: apt cache is up-to-date
      apt:
        update_cache=yes
        cache_valid_time=1

    - name: packages installed
      apt:
        pkg="{{ item }}"
        state=present
      with_items:
        - libguestfs-tools
        - python-cffi
        - libssl-dev
        - jenkins
        - unzip
        - emacs
      register: result
      until: result|success
      retries: 10
      delay: 2

    - name: jenkins is kvm member
      user:
        name=jenkins
        groups=kvm
        append=yes

    - name: jenkins is started
      service: name=jenkins state=restarted

    - name: jenkins is enabled
      service: name=jenkins enabled=yes

    - name: common aliases
      copy:
        dest=/etc/profile.d/aliases.sh
        content="alias ll=\"ls -aul\""
        owner=root
        group=root
        mode=0644

    - name: packer dest directory ready
      file:
        path=/usr/local/bin
        state=directory
        owner=root
        group=staff
        mode=0755

    - name: packer download
      get_url:
        url="http://dl.bintray.com/mitchellh/packer/packer_0.8.1_linux_amd64.zip"
        sha256sum="b85451aa84f20264829916174267ae1642aec434e9a66c382d41e6c595be59d4"
        dest=/tmp/packer.zip
        force=no

    - name: check packer is installed
      stat: path=/usr/local/bin/packer
      register: packer_bin_check

    - name: unzip packer
      when: not packer_bin_check.stat.exists
      unarchive:
        src=/tmp/packer.zip
        dest=/usr/local/bin
        copy=no
        owner=root
        group=staff
        mode=0755

    - name: default sh is bash
      file:
        src=/bin/bash
        dest=/bin/sh
        state=link

    - name: pip packages installed
      pip:
        name="{{ item }}"
      with_items:
        - python-glanceclient
        - python-novaclient
        - python-neutronclient
        - python-heatclient
        - python-openstackclient
        - python-cinderclient

    - name: download jenkins CLI jar file
      get_url:
        url="{{ jenkins_url }}/jnlpJars/jenkins-cli.jar"
        dest=/root/jenkins-cli.jar
        force=no
      register: cli_download
      until: cli_download|success
      retries: 6
      delay: 5

    - name: get jenkins plugin list
      shell: "java -jar /root/jenkins-cli.jar -s {{ jenkins_url }} list-plugins | grep -e ')$' | awk '{ print $1 }' | tr \"\n\" \" \""
      register: list_plugins_output

    - name: update jenkins
      when: list_plugins_output.stdout
      shell: "java -jar /root/jenkins-cli.jar -s {{ jenkins_url }} install-plugin {{ list_plugins_output.stdout }}"

    - name: install jenkins git plugin
      shell: "java -jar /root/jenkins-cli.jar -s {{ jenkins_url }} install-plugin git-client git"

    - name: restart jenkins
      shell: "java -jar /root/jenkins-cli.jar -s {{ jenkins_url }} safe-restart"
