#!/bin/sh

. ../env.sh
. ../functions.sh

uptime_before=$(ssh_vm_execute_cmd $PRIVATE_KEY "$SSH_USER@$IP" "cat /proc/uptime" | awk '{print $1}' | sed "s/\..*//g")

nova reboot --hard $VM_ID

sleep $TIMEOUT

if wait_to_boot $VM_ID $IP; then
    uptime_after=$(ssh_vm_execute_cmd $PRIVATE_KEY "$SSH_USER@$IP" "cat /proc/uptime" | awk '{print $1}' | sed "s/\..*//g")

    if [ "$uptime_before" -gt "$uptime_after" ]; then
        echo "TEST hard reboot  : OK"
        exit 0
    else
        echo "TEST hard reboot  : KO"
        exit 1
    fi
fi

exit 1